# Generated by Django 4.1.7 on 2023-10-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id_familiar', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=False)),
                ('cuota', models.FloatField(default=0)),
                ('descuento', models.IntegerField(default=0)),
            ],
        ),
    ]
