# Generated by Django 4.1.7 on 2023-10-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('precios', '0001_initial'),
        ('familias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nvl_educativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('inicio', models.IntegerField()),
                ('fin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sala_grado_anio', models.CharField(max_length=50)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.division')),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familias.familia')),
                ('nvl_educativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.nvl_educativo')),
                ('turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.turno')),
                ('viaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.precio')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='id_nvl_educativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.nvl_educativo'),
        ),
    ]
