# Generated by Django 4.1.7 on 2023-11-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='vehiculo',
            field=models.BooleanField(default=False),
        ),
    ]
