# Generated by Django 4.1.7 on 2023-11-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_estudiante_vehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='vehiculo',
            new_name='recorrido',
        ),
    ]
