# Generated by Django 4.1.7 on 2023-11-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_rename_vehiculo_estudiante_recorrido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='recorrido',
        ),
    ]
