# Generated by Django 4.1.7 on 2023-10-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('puesto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sueldo', models.FloatField()),
            ],
        ),
    ]
