# Generated by Django 4.1.7 on 2023-10-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=50)),
                ('anio', models.CharField(max_length=50)),
                ('descuento', models.IntegerField()),
                ('total', models.FloatField()),
                ('id_familiar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_familiar_ingresos', to='familias.familia')),
            ],
        ),
    ]
