# Generated by Django 4.1.7 on 2023-10-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='mes',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
