# Generated by Django 4.1.7 on 2023-10-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direcciones', '0001_initial'),
        ('vehiculos', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Viernes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_pasajero_viernes', to='direcciones.direccion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasajero_viernes', to='estudiantes.estudiante')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_viernes', to='vehiculos.vehiculo')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Miercoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_pasajero_miercoles', to='direcciones.direccion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasajero_miercoles', to='estudiantes.estudiante')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_miercoles', to='vehiculos.vehiculo')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Martes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_pasajero_martes', to='direcciones.direccion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasajero_martes', to='estudiantes.estudiante')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_martes', to='vehiculos.vehiculo')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Lunes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_pasajero_lunes', to='direcciones.direccion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasajero_lunes', to='estudiantes.estudiante')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_lunes', to='vehiculos.vehiculo')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Jueves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_pasajero_jueves', to='direcciones.direccion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasajero_jueves', to='estudiantes.estudiante')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_jueves', to='vehiculos.vehiculo')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.viaje')),
            ],
        ),
    ]
