# Generated by Django 4.1.7 on 2023-11-04 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default='2023-01-01')),
                ('motivo', models.IntegerField()),
                ('descripcion', models.IntegerField()),
                ('total', models.FloatField()),
                ('id_vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_vehiculo_gastos', to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Gastos_empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default='2023-01-01')),
                ('total', models.FloatField()),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_empleado_gastos', to='empleados.empleado')),
            ],
        ),
    ]
