# Generated by Django 4.1.7 on 2023-11-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivos_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='gastos_vehiculo',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='gastos_vehiculo',
            name='motivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motivo_vehiculo_gastos', to='gastos.motivos_vehiculo'),
        ),
    ]
