# Generated by Django 4.1.7 on 2023-11-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='celador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celador_de_vehiculo', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chofer_de_vehiculo', to='empleados.empleado'),
        ),
    ]
